<?CUC
	VS(!$_FRFFVBA[VQ]){
		RPUB "<FPEVCG>YBPNGVBA.UERS('?CNTR=YBTVA');</FPEVCG>";
		RKVG();
	}
?>
	<FRPGVBA VQ="VAGEB" PYNFF="VAGEB-FRPGVBA">
        <QVI PYNFF="PBAGNVARE">
            <QVI PYNFF="EBJ">
                <QVI PYNFF="PBY-YT-12">
					<PRAGRE>
                    <U1>ENAX</U1>
					<GNOYR FGLYR="OBEQRE:1CK FBYVQ JUVGR" JVQGU=80%>
						<GE FGLYR="OBEQRE:1CK FBYVQ JUVGR">
							<GU FGLYR="OBEQRE:1CK FBYVQ OYNPX;GRKG-NYVTA:PRAGRE;ONPXTEBHAQ-PBYBE:#SSS"><SBAG PBYBE=#000>ENAX</SBAG></GU>
							<GU FGLYR="OBEQRE:1CK FBYVQ OYNPX;GRKG-NYVTA:PRAGRE;ONPXTEBHAQ-PBYBE:#SSS"><SBAG PBYBE=#000>VQ</SBAG></GU>
							<GU FGLYR="OBEQRE:1CK FBYVQ OYNPX;GRKG-NYVTA:PRAGRE;ONPXTEBHAQ-PBYBE:#SSS"><SBAG PBYBE=#000>CBVAG</SBAG></GU>
							<GU FGLYR="OBEQRE:1CK FBYVQ OYNPX;GRKG-NYVTA:PRAGRE;ONPXTEBHAQ-PBYBE:#SSS"><SBAG PBYBE=#000>YNFGNHGU</SBAG></GU>
						</GE>
						<?CUC
						$FDY = "FRYRPG * SEBZ ZRZORE BEQRE OL CBVAG QRFP, YNFGNHGU NFP YVZVG 0,100";
						$ERFHYG = @ZLFDY_DHREL($FDY);

						SBE($V=1; $YVFG=ZLFDY_SRGPU_NEENL($ERFHYG); $V++){
							VS($YVFG[VQ] == "NQZVA" || $YVFG[CBVAG] == 0)
								PBAGVAHR;
					?>
					<GE NYVTA="PRAGRE">
					<GQ FGLYR="OBEQRE:1CK FBYVQ;" NYVTA="PRAGRE"><SBAG PBYBE=#000><?CUC RPUB $V; ?></SBAG></GQ>
					<GQ FGLYR="OBEQRE:1CK FBYVQ;">
					<SBAG PBYBE=#000><?CUC RPUB $YVFG[VQ]; ?></SBAG></GQ>
					<GQ FGLYR="OBEQRE:1CK FBYVQ;"><SBAG PBYBE=#000><?CUC RPUB $YVFG[CBVAG]; ?></SBAG></GQ>
					<GQ FGLYR="OBEQRE:1CK FBYVQ;"><SBAG PBYBE=#000><?CUC RPUB QNGR("L-Z-Q U\U V\Z F\F",$YVFG[YNFGNHGU]); ?></SBAG></GQ>
					</GE>
					<?CUC
						}
						ZLFDY_SERR_ERFHYG($ERFHYG);
					?>
					</GNOYR>
					</PRAGRE>
                </QVI>
            </QVI>
        </QVI>
